name: Events Demo 1
on: 
  pull_request:
    types:
      - opened
      - closed
    branches:
      - main
      - dev
  workflow_dispatch:
#   push:
#     branches:
#       - main  # main
#       - 'dev*'  # dev-new dev-this-is-new  * means only - can come not /
#       - 'feat/**' # feat/new feat/new/button  ** means as many / can came
#       # devloper-1 will be any of the above type
      
#       # It means that it will not run the workflow then the file from the
      
#       # given path is updated and if we want to update only when this file
#       # path is updated then we can use it in path section.
#    paths-ignore: 
#        - '.github/workflows/*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from Azure DevOps
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.AZURE_SSH_PRIVATE_KEY }}
          known-hosts-data: ${{ secrets.AZURE_SSH_KNOWN_HOSTS }}
        env:
          REPO_URL: "git@ssh.dev.azure.com:v3/vishalchaudhary0011/First%20Project/Testing-Repo-GitHub-Actions"
        run: |
          mkdir my-project
          cd my-project
          git init
          git remote add origin $REPO_URL
          git fetch --depth=1 origin $GITHUB_REF
          git checkout $GITHUB_REF

#         - name: Checkout code
#           uses: actions/checkout@v3
#           with:
#             submodules: 'recursive'
#             ssh-key: ${{ secrets.AZURE_SSH_PRIVATE_KEY }}
#             fetch-depth: 0
#           env:
#             KNOWN_HOSTS_CONTENT: ${{ secrets.AZURE_SSH_KNOWN_HOSTS }}
#       - name: Checkout code from Azure DevOps
#         uses: actions/checkout@v3
#         with:
#           repository: https://dev.azure.com/vishalchaudhary0011/First%20Project/_git/Testing-Repo-GitHub-Actions
#           ref: main
#           ssh-key: ${{ secrets.AZURE_SSH_PRIVATE_KEY }}
#           ssh-known-hosts: ${{ secrets.AZURE_SSH_KNOWN_HOSTS }}
#       - name: Checkout code
#         uses: actions/checkout@v3
#         with:
#           fetch-depth: 0
#           submodules: 'recursive'

#       - name: Set up Azure DevOps PAT
#         run: echo "AZURE_DEVOPS_EXT_PAT=${{ secrets.AZURE_DEVOPS_PAT }}" >> $GITHUB_ENV

#       - name: Push changes to Azure DevOps
#         run: |
#           git remote add azure https://dev.azure.com/vishalchaudhary0011/First%20Project/_git/Testing-Repo-GitHub-Actions
#           git push azure HEAD:refs/heads/master
#       - name: Set Git config
#         run: |
#           git config --global http.sslBackend gnutls
#       - name: Clone Azure DevOps repository
#         run: |
#           git clone git@ssh.dev.azure.com:v3/vishalchaudhary0011/First%20Project/Testing-Repo-GitHub-Actions
#           cd Testing-Repo-GitHub-Actions
#           git checkout main
#         env:
#           AZURE_DEVOPS_EXT_PAT: ${{ secrets.AZURE_DEVOPS_TOKEN }}
#           ssh-key: ${{ secrets.AZURE_SSH_PRIVATE_KEY }}
#           ssh-known-hosts: ${{ secrets.AZURE_SSH_KNOWN_HOSTS }}
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."
